Tweak OpenShift aliases

diff --git a/host_vars/localhost/bashrc.yml b/host_vars/localhost/bashrc.yml
--- a/host_vars/localhost/bashrc.yml
+++ b/host_vars/localhost/bashrc.yml
@@ -37,7 +37,8 @@ my_bashrc: |
       Q=$RHT_OCP4_QUAY_USER
     else
       # Still set the variables, but in a way that newer OCP classes can use them 
-      M=https://api.ocp4.example.com:6443
+M=https://api.ocp4.example.com:6443:59
+
       WC=apps.ocp4.example.com
       NS=nexus.nexus-common.apps.ocp4.example.com
       U=developer
@@ -52,6 +53,29 @@ my_bashrc: |
 
   # Set clustercheck alias for OCP classes
   alias clustercheck="ssh lab@utility ./wait.sh"
+
+  # Set monitoring  aliases
+  alias events='oc get events --sort-by=".lastTimestamp" -n $1'
+  alias podsw='oc get pods -o wide -n $1'
+
+  # OpenShift functions
+  whohas() {
+    local role="$1"
+    if [[ -z "$role" ]]; then
+        echo "Usage: whohas <role>"
+        return 1
+    fi
+
+    oc get clusterrolebindings -o json | jq -r ".items[] | select(.roleRef.name == \"$role\" and .subjects != null) | .subjects[] | \"\(.kind) \(.name)\"" || {
+        echo "Error: Could not find role $role."
+        return 1
+    }
+}
+
+  whomembers() {
+    local group="$1"
+    oc get group "$group" -o json | jq -r '.users[]'
+}
 
   # ===============================
   # Git bash environment variables
